package atlas.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.relocation.BringIntoViewRequester
import androidx.compose.foundation.relocation.bringIntoViewRequester
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import atlas.AppStore
import atlas.core.KnowledgeTree
import atlas.core.KnowledgeTreeNode
import atlas.core.Log
import atlas.core.MdStores.QuestionEntry
import atlas.core.QuestionListModel
import atlas.core.QuestionTags
import atlas.core.SourceQuestions

/** 学习页只负责闪卡复习与卡片浏览；题目管理位于独立的「题库」页。 */
@Composable
fun LearningView(store: AppStore, section: String, onSectionChange: (String) -> Unit) {
    Column(Modifier.fillMaxSize()) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(12.dp), modifier = Modifier.padding(8.dp)) {
            Text("复习", color = Theme.Accent, fontWeight = FontWeight.Bold)
            Spacer(Modifier.weight(1f))
        }
        VDivider()
        ReviewSection(store)
    }
}

@Composable
private fun GenerateQuestionSetDialog(
    questions: List<QuestionEntry>,
    tags: List<String>,
    onDismiss: () -> Unit,
) {
    var countText by remember { mutableStateOf("5") }
    var sourceTag by remember { mutableStateOf("全部") }
    var random by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf<List<QuestionEntry>>(emptyList()) }
    val count = countText.toIntOrNull()?.coerceIn(1, 100) ?: 5
    val candidates = QuestionListModel.visible(questions, sourceTag)

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("生成题库") },
        confirmButton = {
            Button(onClick = {
                generated = QuestionListModel.generateSet(questions, sourceTag, count, random)
            }) { Text(if (generated.isEmpty()) "生成" else "重新生成") }
        },
        dismissButton = { OutlinedButton(onClick = onDismiss) { Text("关闭") } },
        text = {
            Column(
                Modifier.heightIn(max = 560.dp).verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                Text("从现有题库抽取一套练习题，不会修改原题库。", fontSize = 12.sp, color = Theme.Muted)
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text("数量", fontSize = 13.sp)
                    OutlinedTextField(
                        value = countText,
                        onValueChange = { value -> if (value.all { it.isDigit() } && value.length <= 3) countText = value },
                        modifier = Modifier.width(90.dp),
                        singleLine = true,
                    )
                    Text("最多 100 道", fontSize = 11.sp, color = Theme.Muted)
                }
                Text("题目范围", fontSize = 13.sp, fontWeight = FontWeight.SemiBold)
                Row(verticalAlignment = Alignment.CenterVertically) {
                    RadioButton(selected = sourceTag == "全部", onClick = { sourceTag = "全部" })
                    Text("全部")
                    RadioButton(selected = sourceTag != "全部", onClick = { if (sourceTag == "全部") sourceTag = tags.firstOrNull { it != "全部" } ?: "全部" })
                    Text("按标签")
                }
                if (sourceTag != "全部") {
                    Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                        tags.filter { it != "全部" }.forEach { tag ->
                            Text(
                                tag,
                                Modifier
                                    .clickable { sourceTag = tag }
                                    .background(if (sourceTag == tag) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent, MaterialTheme.shapes.small)
                                    .padding(horizontal = 8.dp, vertical = 5.dp),
                                fontSize = 11.sp,
                                color = if (sourceTag == tag) Theme.Accent else Theme.Muted,
                            )
                        }
                    }
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = random, onCheckedChange = { random = it })
                    Text("随机抽取", fontSize = 13.sp)
                    Spacer(Modifier.width(8.dp))
                    Text("可用题目 ${candidates.size} 道", fontSize = 11.sp, color = Theme.Muted)
                }
                if (generated.isNotEmpty()) {
                    VDivider()
                    Text("已生成 ${generated.size} 道", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = Theme.Accent)
                    generated.forEachIndexed { index, question ->
                        Column(
                            Modifier.fillMaxWidth()
                                .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f), MaterialTheme.shapes.small)
                                .padding(10.dp),
                        ) {
                            Text("${index + 1}. ${question.q}", fontSize = 13.sp, fontWeight = FontWeight.SemiBold)
                            if (question.tags.isNotEmpty()) Text(question.tags.joinToString("、"), fontSize = 10.sp, color = Theme.Muted)
                        }
                    }
                } else if (candidates.isEmpty()) {
                    Text("当前范围没有可抽取的题目。", fontSize = 12.sp, color = Theme.WarnOrange)
                }
            }
        },
    )
}

// ---------------- 题库（中心信息源：题目+答案，派生面试/闪卡/复习） ----------------

@Composable
private fun LegacyQuestionSection(store: AppStore) {
    var showImport by remember { mutableStateOf(false) }
    var showGenerate by remember { mutableStateOf(false) }
    var editing by remember { mutableStateOf<QuestionEntry?>(null) }
    var deleting by remember { mutableStateOf<QuestionEntry?>(null) }
    var expandedIds by remember { mutableStateOf<Set<String>>(emptySet()) } // 支持同时展开多个条目
    var query by remember { mutableStateOf("") }
    var tagFilter by remember { mutableStateOf("全部") }
    var grouped by remember { mutableStateOf(false) }
    val tags = listOf("全部") + (QuestionTags.BUILT_IN + store.questions.flatMap { it.tags }).distinct().sorted()
    val visible = QuestionListModel.visible(store.questions, tagFilter, query)
    val visibleOrder = visible.mapIndexed { index, question -> question.id to (index + 1) }.toMap()
    val visibleGroups: List<Pair<String, List<QuestionEntry>>> = if (grouped) {
        QuestionListModel.groups(visible).map { it.key to it.value }
    } else {
        listOf("" to visible)
    }
    val untested = store.questions.count { it.status == "未测" }
    val retest = store.questions.count { it.status == "待复测" }
    val stable = store.questions.count { it.status == "已稳定" }
    Column(Modifier.fillMaxSize().padding(8.dp)) {
        OutlinedTextField(
            value = query,
            onValueChange = { query = it },
            modifier = Modifier.fillMaxWidth(),
            placeholder = { Text("搜索题目关键词…") },
            singleLine = true,
        )
        Spacer(Modifier.height(8.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), verticalAlignment = Alignment.CenterVertically) {
            Button(onClick = { Log.d("打开导入题单对话框"); showImport = true }) { Text("+ 导入题单") }
            OutlinedButton(onClick = { Log.d("打开生成题库对话框"); showGenerate = true }) { Text("生成题库") }
            Text("点击题目展开详情与操作", fontSize = 11.sp, color = Theme.Muted)
        }
        Row(Modifier.padding(top = 4.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {
            Text("共 ${store.questions.size} 题 · 未测 $untested · 待复测 $retest · 已稳定 $stable", fontSize = 11.sp, color = Theme.Muted)
            Spacer(Modifier.weight(1f))
            Text("标签:", fontSize = 11.sp, color = Theme.Muted)
            tags.forEach { tag ->
                Text(tag, Modifier
                    .clickable { tagFilter = tag }
                    .background(if (tagFilter == tag) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent, MaterialTheme.shapes.small)
                    .padding(horizontal = 8.dp, vertical = 3.dp), fontSize = 11.sp,
                    color = if (tagFilter == tag) Theme.Accent else Theme.Muted)
            }
            Spacer(Modifier.weight(1f))
            Text(if (grouped) "列表视图" else "按标签分组", Modifier.clickable { grouped = !grouped }, fontSize = 11.sp, color = Theme.Accent)
        }
        Spacer(Modifier.height(8.dp))
        LazyColumn(Modifier.fillMaxSize(), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            if (visible.isEmpty()) {
                item { Text("没有匹配的题目。", fontSize = 13.sp, color = Theme.Muted) }
            }
            visibleGroups.forEach { (group, questions) ->
                if (grouped) {
                    item(key = "group:$group") {
                        Text("$group（${questions.size}）", Modifier.padding(top = 4.dp), fontSize = 12.sp, fontWeight = FontWeight.Bold, color = Theme.Accent)
                    }
                }
                items(questions, key = { if (grouped) "$group:${it.id}" else it.id }) { q ->
                val expanded = q.id in expandedIds
                val order = visibleOrder[q.id] ?: 0
                Column(
                    Modifier.fillMaxWidth()
                        .background(
                            if (expanded) Theme.Accent.copy(alpha = 0.08f) else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
                            MaterialTheme.shapes.small,
                        )
                        .clickable {
                            Log.d("题目条目点击 ${q.q.take(16)} 展开=$expanded")
                            expandedIds = if (expanded) expandedIds - q.id else expandedIds + q.id
                        }
                        .padding(8.dp),
                ) {
                    // 收起态：题面 + 状态。操作全部收进展开详情，列表保持一眼可扫
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text(
                            "$order",
                            modifier = Modifier.width(28.dp),
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            color = Theme.Muted,
                        )
                        Column(Modifier.weight(1f)) {
                            Text(
                                q.q,
                                fontSize = 13.sp,
                                fontWeight = FontWeight.SemiBold,
                                color = if (expanded) Theme.Accent else MaterialTheme.colorScheme.onSurface,
                            )
                            if (q.tags.isNotEmpty()) Text("标签：${q.tags.joinToString("、")}", fontSize = 10.sp, color = Theme.Accent, maxLines = 1)
                        }
                        StatusChip(
                            q.status,
                            when (q.status) { "已稳定" -> Theme.OkGreen; "待复测" -> Theme.WarnOrange; else -> Theme.Muted },
                        )
                    }
                    if (expanded) {
                        Spacer(Modifier.height(6.dp))
                        VDivider()
                        Spacer(Modifier.height(6.dp))
                        // 展开后直接显示答案，不再增加“显示答案”的二次点击。
                        if (q.answer.isNotBlank()) {
                            Surface(
                                modifier = Modifier.fillMaxWidth(),
                                shape = MaterialTheme.shapes.small,
                                color = Theme.OkGreen.copy(alpha = 0.08f),
                            ) {
                                Column(Modifier.padding(horizontal = 12.dp, vertical = 10.dp)) {
                                    Text("答案", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = Theme.OkGreen)
                                    Spacer(Modifier.height(4.dp))
                                    CompositionLocalProvider(LocalContentColor provides Theme.OkGreen.copy(alpha = 0.92f)) {
                                        MarkdownText(q.answer)
                                    }
                                }
                            }
                        } else {
                            Text("还没有答案 · 点「编辑」补全（转闪卡与复习要用）", fontSize = 11.sp, color = Theme.WarnOrange)
                        }
                        if (q.ref.isNotBlank()) Text("参考要点:${q.ref.take(120)}", fontSize = 10.sp, color = Theme.Muted, maxLines = 3)
                        q.logs.takeLast(3).forEach { Text("- $it", fontSize = 10.sp, color = Theme.Muted, maxLines = 1) }
                        Spacer(Modifier.height(6.dp))
                        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                            Text("转闪卡复习", Modifier.clickable { store.questionToCard(q) }, fontSize = 13.sp, color = Theme.OkGreen)
                            Text("编辑", Modifier.clickable { Log.d("打开题目编辑对话框 ${q.q.take(16)}"); editing = q }, fontSize = 13.sp, color = Theme.Muted)
                            Text("删除", Modifier.clickable { Log.d("打开题目删除确认 ${q.q.take(16)}"); deleting = q }, fontSize = 13.sp, color = Theme.BadRed)
                        }
                    }
                }
            }
            }
        }
    }
    if (showImport) ImportQuestionsDialog(store) { showImport = false }
    if (showGenerate) GenerateQuestionSetDialog(store.questions, tags) { showGenerate = false }
    editing?.let { q -> EditQuestionDialog(store, q) { editing = null } }
    deleting?.let { q ->
        AlertDialog(
            onDismissRequest = { deleting = null },
            title = { Text("删除题目") },
            text = { Text("确定删除「${q.q.take(30)}」？") },
            confirmButton = { Button(onClick = { store.deleteQuestion(q.id); deleting = null }) { Text("删除") } },
            dismissButton = { OutlinedButton(onClick = { deleting = null }) { Text("取消") } },
        )
    }
}

/** 同源题目页：左侧映射 knowledge-base 文档，题目内容直接来自当前源 Markdown。 */
private sealed interface SourceDocumentItem {
    val startOffset: Int

    data class Question(val entry: SourceQuestions.Entry) : SourceDocumentItem {
        override val startOffset: Int get() = entry.startOffset
    }

    data class Section(val heading: SourceQuestions.SectionHeading) : SourceDocumentItem {
        override val startOffset: Int get() = heading.startOffset
    }
}

private enum class QuestionSearchScope(val label: String) {
    CURRENT("当前文件"),
    ALL("整个目录树"),
}

@Composable
fun QuestionSection(store: AppStore) {
    var query by remember { mutableStateOf("") }
    var expanded by remember { mutableStateOf<Set<String>>(emptySet()) }
    var expandedDirs by remember { mutableStateOf(setOf("knowledge-base")) }
    var editing by remember { mutableStateOf<SourceQuestions.Entry?>(null) }
    var searchScope by remember { mutableStateOf(QuestionSearchScope.ALL) }
    val searchPool = if (searchScope == QuestionSearchScope.ALL) store.allSourceQuestions else store.sourceQuestions
    val visible = if (query.isBlank()) store.sourceQuestions else searchPool.filter { it.question.contains(query.trim(), ignoreCase = true) }
    val documentItems = buildList<SourceDocumentItem> {
        visible.forEach { add(SourceDocumentItem.Question(it)) }
        if (query.isBlank()) store.sourceSections.forEach { add(SourceDocumentItem.Section(it)) }
    }.sortedBy { it.startOffset }
    val knowledgeTree = remember(store.knowledgeDocuments.toList()) {
        KnowledgeTree.build(store.knowledgeDocuments)
    }

    fun locateSource(path: String) {
        expandedDirs = expandedDirs + setOf("knowledge-base") + KnowledgeTree.ancestorPaths(path)
        store.selectSourceDocument(path)
    }

    LaunchedEffect(store.selectedSourcePath, store.knowledgeDocuments.toList()) {
        expandedDirs = expandedDirs + KnowledgeTree.ancestorPaths(store.selectedSourcePath)
    }

    Row(Modifier.fillMaxSize().padding(8.dp)) {
        Column(Modifier.width(270.dp).fillMaxHeight()) {
            Text("知识库文档", fontWeight = FontWeight.Bold, color = Theme.Accent)
            Text("knowledge-base · ${store.knowledgeDocuments.size} 篇", fontSize = 12.sp, color = Theme.Muted)
            Spacer(Modifier.height(10.dp))
            LazyColumn(verticalArrangement = Arrangement.spacedBy(3.dp)) {
                item(key = knowledgeTree.path) {
                    KnowledgeTreeNodeView(
                        node = knowledgeTree,
                        depth = 0,
                        expandedDirs = expandedDirs,
                        selectedPath = store.selectedSourcePath,
                        onToggleDirectory = { path ->
                            expandedDirs = if (path in expandedDirs) expandedDirs - path else expandedDirs + path
                        },
                        onSelectFile = { path ->
                            expanded = emptySet()
                            query = ""
                            locateSource(path)
                        },
                    )
                }
            }
        }
        Spacer(Modifier.width(10.dp))
        Box(Modifier.fillMaxHeight().width(1.dp).background(MaterialTheme.colorScheme.outlineVariant))
        Spacer(Modifier.width(10.dp))
        Column(Modifier.weight(1f).fillMaxHeight()) {
        OutlinedTextField(
            value = query,
            onValueChange = { query = it },
            modifier = Modifier.fillMaxWidth(),
            placeholder = { Text("搜索题目关键词…") },
            singleLine = true,
        )
        Spacer(Modifier.height(8.dp))
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("搜索范围", fontSize = 12.sp, color = Theme.Muted)
            QuestionSearchScope.entries.forEach { scope ->
                val active = searchScope == scope
                Text(
                    scope.label,
                    Modifier
                        .clickable { searchScope = scope }
                        .background(if (active) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent, MaterialTheme.shapes.small)
                        .padding(horizontal = 9.dp, vertical = 4.dp),
                    fontSize = 12.sp,
                    color = if (active) Theme.Accent else Theme.Muted,
                    fontWeight = if (active) FontWeight.Bold else FontWeight.Normal,
                )
            }
        }
        Spacer(Modifier.height(6.dp))
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("同源题库", fontWeight = FontWeight.Bold, color = Theme.Accent)
            Text("${if (query.isBlank()) store.sourceQuestions.size else visible.size} 题", fontSize = 11.sp, color = Theme.Muted)
            Spacer(Modifier.weight(1f))
            Text("${store.selectedSourcePath} · 文件即题库", fontSize = 10.sp, color = Theme.Muted, maxLines = 1)
        }
        Spacer(Modifier.height(6.dp))
        if (SourceQuestions.isSupportedPath(store.selectedSourcePath, store.settings.sourceQuestionPaths)) {
            Text("点击题目显示答案；编辑会直接写回源 Markdown。", fontSize = 11.sp, color = Theme.Muted)
        } else {
            Text("该文档已纳入目录映射，但当前版本暂未接入 Q 题目解析。", fontSize = 11.sp, color = Theme.WarnOrange)
        }
        Spacer(Modifier.height(8.dp))
        LazyColumn(Modifier.fillMaxSize(), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            if (visible.isEmpty()) item { Text("没有匹配的题目。", fontSize = 13.sp, color = Theme.Muted) }
            items(documentItems, key = { item ->
                when (item) {
                    is SourceDocumentItem.Question -> item.entry.id
                    is SourceDocumentItem.Section -> "section:${item.heading.startOffset}"
                }
            }) { item ->
                if (item is SourceDocumentItem.Section) {
                    Row(
                        Modifier.fillMaxWidth()
                            .background(Theme.Accent.copy(alpha = 0.1f), MaterialTheme.shapes.small)
                            .padding(horizontal = 12.dp, vertical = 9.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text("§", color = Theme.Accent, fontWeight = FontWeight.Bold)
                        Spacer(Modifier.width(8.dp))
                        Text(item.heading.title, color = Theme.Accent, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                    }
                    return@items
                }
                val entry = (item as SourceDocumentItem.Question).entry
                val isExpanded = entry.id in expanded
                Column(
                    Modifier.fillMaxWidth()
                        .background(
                            if (isExpanded) Theme.Accent.copy(alpha = 0.08f)
                            else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
                            MaterialTheme.shapes.small,
                        )
                        .clickable {
                            locateSource(entry.sourcePath)
                            expanded = if (isExpanded) expanded - entry.id else expanded + entry.id
                        }
                        .padding(10.dp),
                ) {
                    Text("Q${entry.number}", fontSize = 11.sp, color = Theme.Muted)
                    Spacer(Modifier.height(2.dp))
                    Text(entry.question, fontSize = 13.sp, fontWeight = FontWeight.SemiBold)
                    if (searchScope == QuestionSearchScope.ALL && query.isNotBlank()) {
                        Text(entry.sourcePath, fontSize = 10.sp, color = Theme.Accent, maxLines = 1)
                    }
                    if (isExpanded) {
                        Text("源文件已定位：${entry.sourcePath}", fontSize = 10.sp, color = Theme.Accent, maxLines = 1)
                        Spacer(Modifier.height(8.dp))
                        VDivider()
                        Spacer(Modifier.height(8.dp))
                        if (entry.answer.isBlank()) {
                            Text("暂无答案", fontSize = 12.sp, color = Theme.WarnOrange)
                        } else {
                            Surface(
                                Modifier.fillMaxWidth(),
                                shape = MaterialTheme.shapes.small,
                                color = Theme.OkGreen.copy(alpha = 0.08f),
                            ) {
                                Column(Modifier.padding(horizontal = 12.dp, vertical = 10.dp)) {
                                    Text("答案", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = Theme.OkGreen)
                                    Spacer(Modifier.height(4.dp))
                                    CompositionLocalProvider(LocalContentColor provides Theme.OkGreen.copy(alpha = 0.92f)) {
                                        MarkdownText(entry.answer)
                                    }
                                }
                            }
                        }
                        Spacer(Modifier.height(8.dp))
                        Text("编辑", Modifier.clickable { editing = entry }, fontSize = 13.sp, color = Theme.Accent)
                    }
                }
            }
        }
    }
    }
    editing?.let { entry ->
        EditSourceQuestionDialog(store, entry) { editing = null }
    }
}

@Composable
private fun KnowledgeTreeNodeView(
    node: KnowledgeTreeNode,
    depth: Int,
    expandedDirs: Set<String>,
    selectedPath: String,
    onToggleDirectory: (String) -> Unit,
    onSelectFile: (String) -> Unit,
) {
    val isExpanded = node.path in expandedDirs
    val selected = !node.isDirectory && node.path == selectedPath
    val bringIntoViewRequester = remember { BringIntoViewRequester() }
    LaunchedEffect(selected) {
        if (selected) bringIntoViewRequester.bringIntoView()
    }
    Row(
        Modifier.fillMaxWidth()
            .bringIntoViewRequester(bringIntoViewRequester)
            .background(
                if (selected) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent,
                MaterialTheme.shapes.small,
            )
            .clickable {
                if (node.isDirectory) onToggleDirectory(node.path) else onSelectFile(node.path)
            }
            .padding(start = (depth * 16).dp, end = 6.dp, top = 7.dp, bottom = 7.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            if (node.isDirectory) (if (isExpanded) "▾" else "▸") else "  ",
            modifier = Modifier.width(18.dp), color = Theme.Muted, fontSize = 13.sp,
        )
        Text(
            if (node.isDirectory) "▰" else "M↓",
            modifier = Modifier.width(28.dp),
            color = if (selected) Theme.Accent else Theme.Muted,
            fontSize = if (node.isDirectory) 13.sp else 10.sp,
        )
        Text(
            node.name,
            color = if (selected) Theme.Accent else MaterialTheme.colorScheme.onSurface,
            fontSize = if (node.isDirectory) 14.sp else 13.sp,
            maxLines = 2,
        )
    }
    if (node.isDirectory && isExpanded) {
        node.children.forEach { child ->
            KnowledgeTreeNodeView(child, depth + 1, expandedDirs, selectedPath, onToggleDirectory, onSelectFile)
        }
    }
}

@Composable
private fun EditSourceQuestionDialog(
    store: AppStore,
    entry: SourceQuestions.Entry,
    onDismiss: () -> Unit,
) {
    var question by remember(entry.id) { mutableStateOf(entry.question) }
    var answer by remember(entry.id) { mutableStateOf(entry.answer) }
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("编辑 Q${entry.number}") },
        confirmButton = {
            Button(onClick = {
                if (question.isNotBlank()) store.saveSourceQuestion(entry, question, answer)
                onDismiss()
            }) { Text("保存到源文档") }
        },
        dismissButton = { OutlinedButton(onClick = onDismiss) { Text("取消") } },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(question, { question = it }, Modifier.fillMaxWidth(), label = { Text("题目") }, minLines = 2)
                OutlinedTextField(answer, { answer = it }, Modifier.fillMaxWidth(), label = { Text("答案 Markdown") }, minLines = 8)
                Text("保存后直接修改 ${entry.sourcePath}", fontSize = 11.sp, color = Theme.Muted)
            }
        },
    )
}
