package atlas.ui

import androidx.compose.animation.core.animateDpAsState
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.relocation.BringIntoViewRequester
import androidx.compose.foundation.relocation.bringIntoViewRequester
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.onGloballyPositioned
import androidx.compose.ui.layout.positionInParent
import androidx.compose.ui.zIndex
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.PointerEventPass
import androidx.compose.ui.input.pointer.isSecondaryPressed
import androidx.compose.ui.input.pointer.positionChanged
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.KeyEventType
import androidx.compose.ui.input.key.key
import androidx.compose.ui.input.key.type
import androidx.compose.ui.input.key.onPreviewKeyEvent
import androidx.compose.ui.window.DialogProperties
import atlas.AppStore
import atlas.core.KnowledgeTree
import atlas.core.KnowledgeTreeNode
import atlas.core.Log
import atlas.core.MdStores.QuestionEntry
import atlas.core.QuestionListModel
import atlas.core.QuestionTags
import atlas.core.SourceQuestions

/** 学习页只负责闪卡复习与卡片浏览；题目管理位于独立的「题库」页。 */
@Composable
fun LearningView(store: AppStore, section: String, onSectionChange: (String) -> Unit) {
    Column(Modifier.fillMaxSize()) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(12.dp), modifier = Modifier.padding(8.dp)) {
            Text("复习", color = Theme.Accent, fontWeight = FontWeight.Bold)
            Spacer(Modifier.weight(1f))
        }
        VDivider()
        ReviewSection(store)
    }
}

@Composable
private fun GenerateQuestionSetDialog(
    questions: List<QuestionEntry>,
    tags: List<String>,
    onDismiss: () -> Unit,
) {
    var countText by remember { mutableStateOf("5") }
    var sourceTag by remember { mutableStateOf("全部") }
    var random by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf<List<QuestionEntry>>(emptyList()) }
    val count = countText.toIntOrNull()?.coerceIn(1, 100) ?: 5
    val candidates = QuestionListModel.visible(questions, sourceTag)

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("生成题库") },
        confirmButton = {
            Button(onClick = {
                generated = QuestionListModel.generateSet(questions, sourceTag, count, random)
            }) { Text(if (generated.isEmpty()) "生成" else "重新生成") }
        },
        dismissButton = { OutlinedButton(onClick = onDismiss) { Text("关闭") } },
        text = {
            Column(
                Modifier.heightIn(max = 560.dp).verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                Text("从现有题库抽取一套练习题，不会修改原题库。", fontSize = 12.sp, color = Theme.Muted)
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text("数量", fontSize = 13.sp)
                    OutlinedTextField(
                        value = countText,
                        onValueChange = { value -> if (value.all { it.isDigit() } && value.length <= 3) countText = value },
                        modifier = Modifier.width(90.dp),
                        singleLine = true,
                    )
                    Text("最多 100 道", fontSize = 11.sp, color = Theme.Muted)
                }
                Text("题目范围", fontSize = 13.sp, fontWeight = FontWeight.SemiBold)
                Row(verticalAlignment = Alignment.CenterVertically) {
                    RadioButton(selected = sourceTag == "全部", onClick = { sourceTag = "全部" })
                    Text("全部")
                    RadioButton(selected = sourceTag != "全部", onClick = { if (sourceTag == "全部") sourceTag = tags.firstOrNull { it != "全部" } ?: "全部" })
                    Text("按标签")
                }
                if (sourceTag != "全部") {
                    Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                        tags.filter { it != "全部" }.forEach { tag ->
                            Text(
                                tag,
                                Modifier
                                    .clickable { sourceTag = tag }
                                    .background(if (sourceTag == tag) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent, MaterialTheme.shapes.small)
                                    .padding(horizontal = 8.dp, vertical = 5.dp),
                                fontSize = 11.sp,
                                color = if (sourceTag == tag) Theme.Accent else Theme.Muted,
                            )
                        }
                    }
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = random, onCheckedChange = { random = it })
                    Text("随机抽取", fontSize = 13.sp)
                    Spacer(Modifier.width(8.dp))
                    Text("可用题目 ${candidates.size} 道", fontSize = 11.sp, color = Theme.Muted)
                }
                if (generated.isNotEmpty()) {
                    VDivider()
                    Text("已生成 ${generated.size} 道", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = Theme.Accent)
                    generated.forEachIndexed { index, question ->
                        Column(
                            Modifier.fillMaxWidth()
                                .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f), MaterialTheme.shapes.small)
                                .padding(10.dp),
                        ) {
                            Text("${index + 1}. ${question.q}", fontSize = 13.sp, fontWeight = FontWeight.SemiBold)
                            if (question.tags.isNotEmpty()) Text(question.tags.joinToString("、"), fontSize = 10.sp, color = Theme.Muted)
                        }
                    }
                } else if (candidates.isEmpty()) {
                    Text("当前范围没有可抽取的题目。", fontSize = 12.sp, color = Theme.WarnOrange)
                }
            }
        },
    )
}

// ---------------- 题库（中心信息源：题目+答案，派生面试/闪卡/复习） ----------------

@Composable
private fun LegacyQuestionSection(store: AppStore) {
    var showImport by remember { mutableStateOf(false) }
    var showGenerate by remember { mutableStateOf(false) }
    var editing by remember { mutableStateOf<QuestionEntry?>(null) }
    var deleting by remember { mutableStateOf<QuestionEntry?>(null) }
    var expandedIds by remember { mutableStateOf<Set<String>>(emptySet()) } // 支持同时展开多个条目
    var query by remember { mutableStateOf("") }
    var tagFilter by remember { mutableStateOf("全部") }
    var grouped by remember { mutableStateOf(false) }
    val tags = listOf("全部") + (QuestionTags.BUILT_IN + store.questions.flatMap { it.tags }).distinct().sorted()
    val visible = QuestionListModel.visible(store.questions, tagFilter, query)
    val visibleOrder = visible.mapIndexed { index, question -> question.id to (index + 1) }.toMap()
    val visibleGroups: List<Pair<String, List<QuestionEntry>>> = if (grouped) {
        QuestionListModel.groups(visible).map { it.key to it.value }
    } else {
        listOf("" to visible)
    }
    val untested = store.questions.count { it.status == "未测" }
    val retest = store.questions.count { it.status == "待复测" }
    val stable = store.questions.count { it.status == "已稳定" }
    Column(Modifier.fillMaxSize().padding(8.dp)) {
        OutlinedTextField(
            value = query,
            onValueChange = { query = it },
            modifier = Modifier.fillMaxWidth(),
            placeholder = { Text("搜索题目关键词…") },
            singleLine = true,
        )
        Spacer(Modifier.height(8.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), verticalAlignment = Alignment.CenterVertically) {
            Button(onClick = { Log.d("打开导入题单对话框"); showImport = true }) { Text("+ 导入题单") }
            OutlinedButton(onClick = { Log.d("打开生成题库对话框"); showGenerate = true }) { Text("生成题库") }
            Text("点击题目展开详情与操作", fontSize = 11.sp, color = Theme.Muted)
        }
        Row(Modifier.padding(top = 4.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {
            Text("共 ${store.questions.size} 题 · 未测 $untested · 待复测 $retest · 已稳定 $stable", fontSize = 11.sp, color = Theme.Muted)
            Spacer(Modifier.weight(1f))
            Text("标签:", fontSize = 11.sp, color = Theme.Muted)
            tags.forEach { tag ->
                Text(tag, Modifier
                    .clickable { tagFilter = tag }
                    .background(if (tagFilter == tag) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent, MaterialTheme.shapes.small)
                    .padding(horizontal = 8.dp, vertical = 3.dp), fontSize = 11.sp,
                    color = if (tagFilter == tag) Theme.Accent else Theme.Muted)
            }
            Spacer(Modifier.weight(1f))
            Text(if (grouped) "列表视图" else "按标签分组", Modifier.clickable { grouped = !grouped }, fontSize = 11.sp, color = Theme.Accent)
        }
        Spacer(Modifier.height(8.dp))
        LazyColumn(Modifier.fillMaxSize(), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            if (visible.isEmpty()) {
                item { Text("没有匹配的题目。", fontSize = 13.sp, color = Theme.Muted) }
            }
            visibleGroups.forEach { (group, questions) ->
                if (grouped) {
                    item(key = "group:$group") {
                        Text("$group（${questions.size}）", Modifier.padding(top = 4.dp), fontSize = 12.sp, fontWeight = FontWeight.Bold, color = Theme.Accent)
                    }
                }
                items(questions, key = { if (grouped) "$group:${it.id}" else it.id }) { q ->
                val expanded = q.id in expandedIds
                val order = visibleOrder[q.id] ?: 0
                Column(
                    Modifier.fillMaxWidth()
                        .background(
                            if (expanded) Theme.Accent.copy(alpha = 0.08f) else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
                            MaterialTheme.shapes.small,
                        )
                        .clickable {
                            Log.d("题目条目点击 ${q.q.take(16)} 展开=$expanded")
                            expandedIds = if (expanded) expandedIds - q.id else expandedIds + q.id
                        }
                        .padding(8.dp),
                ) {
                    // 收起态：题面 + 状态。操作全部收进展开详情，列表保持一眼可扫
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text(
                            "$order",
                            modifier = Modifier.width(28.dp),
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            color = Theme.Muted,
                        )
                        Column(Modifier.weight(1f)) {
                            Text(
                                q.q,
                                fontSize = 13.sp,
                                fontWeight = FontWeight.SemiBold,
                                color = if (expanded) Theme.Accent else MaterialTheme.colorScheme.onSurface,
                            )
                            if (q.tags.isNotEmpty()) Text("标签：${q.tags.joinToString("、")}", fontSize = 10.sp, color = Theme.Accent, maxLines = 1)
                        }
                        StatusChip(
                            q.status,
                            when (q.status) { "已稳定" -> Theme.OkGreen; "待复测" -> Theme.WarnOrange; else -> Theme.Muted },
                        )
                    }
                    if (expanded) {
                        Spacer(Modifier.height(6.dp))
                        VDivider()
                        Spacer(Modifier.height(6.dp))
                        // 展开后直接显示答案，不再增加“显示答案”的二次点击。
                        if (q.answer.isNotBlank()) {
                            Surface(
                                modifier = Modifier.fillMaxWidth(),
                                shape = MaterialTheme.shapes.small,
                                color = Theme.OkGreen.copy(alpha = 0.08f),
                            ) {
                                Column(Modifier.padding(horizontal = 12.dp, vertical = 10.dp)) {
                                    Text("答案", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = if (store.settings.markdownStyle == "classic") Theme.OkGreen else Theme.Accent)
                                    Spacer(Modifier.height(4.dp))
                                    CompositionLocalProvider(
                                        LocalContentColor provides if (store.settings.markdownStyle == "classic") {
                                            Theme.OkGreen.copy(alpha = 0.92f)
                                        } else {
                                            MaterialTheme.colorScheme.onSurface
                                        },
                                    ) {
                                        MarkdownText(q.answer, style = store.settings.markdownStyle)
                                    }
                                }
                            }
                        } else {
                            Text("还没有答案 · 点「编辑」补全（转闪卡与复习要用）", fontSize = 11.sp, color = Theme.WarnOrange)
                        }
                        if (q.ref.isNotBlank()) Text("参考要点:${q.ref.take(120)}", fontSize = 10.sp, color = Theme.Muted, maxLines = 3)
                        q.logs.takeLast(3).forEach { Text("- $it", fontSize = 10.sp, color = Theme.Muted, maxLines = 1) }
                        Spacer(Modifier.height(6.dp))
                        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                            Text("转闪卡复习", Modifier.clickable { store.questionToCard(q) }, fontSize = 13.sp, color = Theme.OkGreen)
                            Text("编辑", Modifier.clickable { Log.d("打开题目编辑对话框 ${q.q.take(16)}"); editing = q }, fontSize = 13.sp, color = Theme.Muted)
                            Text("删除", Modifier.clickable { Log.d("打开题目删除确认 ${q.q.take(16)}"); deleting = q }, fontSize = 13.sp, color = Theme.BadRed)
                        }
                    }
                }
            }
            }
        }
    }
    if (showImport) ImportQuestionsDialog(store) { showImport = false }
    if (showGenerate) GenerateQuestionSetDialog(store.questions, tags) { showGenerate = false }
    editing?.let { q -> EditQuestionDialog(store, q) { editing = null } }
    deleting?.let { q ->
        AlertDialog(
            onDismissRequest = { deleting = null },
            title = { Text("删除题目") },
            text = { Text("确定删除「${q.q.take(30)}」？") },
            confirmButton = { Button(onClick = { store.deleteQuestion(q.id); deleting = null }) { Text("删除") } },
            dismissButton = { OutlinedButton(onClick = { deleting = null }) { Text("取消") } },
        )
    }
}

/** 同源题目页：左侧映射 knowledge-base 文档，题目内容直接来自当前源 Markdown。 */
private sealed interface SourceDocumentItem {
    val startOffset: Int

    data class Question(val entry: SourceQuestions.Entry) : SourceDocumentItem {
        override val startOffset: Int get() = entry.startOffset
    }

    data class Section(val heading: SourceQuestions.SectionHeading) : SourceDocumentItem {
        override val startOffset: Int get() = heading.startOffset
    }
}

private enum class QuestionSearchScope(val label: String) {
    CURRENT("当前文件"),
    ALL("整个目录树"),
}

/** 列表 key 必须区分同一源文件中重复题号的不同题目。 */
internal fun sourceQuestionKey(entry: SourceQuestions.Entry): String =
    "${entry.sourcePath}#${entry.startOffset}"

internal fun adjacentQuestionIndex(currentIndex: Int, total: Int, delta: Int): Int? {
    val next = currentIndex + delta
    return next.takeIf { total > 0 && it in 0 until total }
}

internal fun safeQuestionIndex(currentIndex: Int, total: Int): Int? =
    currentIndex.takeIf { total > 0 }?.coerceIn(0, total - 1)

internal fun canNavigateQuestionEditor(isSaving: Boolean, targetIndex: Int, total: Int): Boolean =
    !isSaving && targetIndex in 0 until total

@Composable
fun QuestionSection(store: AppStore) {
    val ui = atlasUiTokens()
    var query by remember { mutableStateOf("") }
    var expanded by remember { mutableStateOf<Set<String>>(emptySet()) }
    var expandedDirs by remember { mutableStateOf(setOf("knowledge-base")) }
    var renameTarget by remember { mutableStateOf<KnowledgeTreeNode?>(null) }
    var editingEntry by remember { mutableStateOf<SourceQuestions.Entry?>(null) }
    var showCreateSingle by remember { mutableStateOf(false) }
    var showCreateBatch by remember { mutableStateOf(false) }
    var showMoreActions by remember { mutableStateOf(false) }
    var searchScope by remember { mutableStateOf(QuestionSearchScope.ALL) }
    var reorderMode by remember { mutableStateOf(false) }
    var draggingKey by remember { mutableStateOf<String?>(null) }
    var dragTargetIndex by remember { mutableStateOf<Int?>(null) }
    var dragPointerY by remember { mutableStateOf(0f) }
    var dragGrabOffset by remember { mutableStateOf(0f) }
    val cardTops = remember { mutableStateMapOf<String, Float>() }
    val searchPool = if (searchScope == QuestionSearchScope.ALL) store.allSourceQuestions else store.sourceQuestions
    val visible = if (query.isBlank()) store.sourceQuestions else searchPool.filter { it.question.contains(query.trim(), ignoreCase = true) }
    val renderedQuestions = if (reorderMode && draggingKey != null && query.isBlank()) {
        val from = visible.indexOfFirst { sourceQuestionKey(it) == draggingKey }
        val to = dragTargetIndex
        if (from >= 0 && to != null && to in visible.indices && from != to) {
            visible.toMutableList().apply { add(to, removeAt(from)) }
        } else visible
    } else visible
    val documentItems = buildList<SourceDocumentItem> {
        renderedQuestions.forEach { add(SourceDocumentItem.Question(it)) }
        if (query.isBlank() && !(reorderMode && draggingKey != null)) {
            store.sourceSections.forEach { add(SourceDocumentItem.Section(it)) }
        }
    }.sortedBy { it.startOffset }
    val mappedDocuments = remember(store.knowledgeDocuments.toList(), store.settings.sourceQuestionPaths) {
        SourceQuestions.supportedDocuments(store.knowledgeDocuments, store.settings.sourceQuestionPaths)
    }
    val knowledgeTree = remember(mappedDocuments) {
        KnowledgeTree.build(mappedDocuments)
    }
    val selectedMappedDocument = store.selectedSourcePath.takeIf { it in mappedDocuments }.orEmpty()

    fun locateSource(path: String) {
        expandedDirs = expandedDirs + setOf("knowledge-base") + KnowledgeTree.ancestorPaths(path)
        store.selectSourceDocument(path)
    }

    LaunchedEffect(store.selectedSourcePath, mappedDocuments) {
        expandedDirs = expandedDirs + KnowledgeTree.ancestorPaths(store.selectedSourcePath)
    }

    Row(Modifier.fillMaxSize().padding(ui.spacing.page)) {
        Column(Modifier.width(270.dp).fillMaxHeight()) {
            Text("知识库文档", fontWeight = FontWeight.Bold, color = Theme.Accent)
            Text("题库映射 · ${mappedDocuments.size} 篇", fontSize = 12.sp, color = Theme.Muted)
            if (mappedDocuments.isEmpty()) {
                Text("当前配置没有匹配的 Markdown 文档，请到设置中添加文件或目录。", fontSize = 11.sp, color = Theme.WarnOrange)
            }
            Spacer(Modifier.height(10.dp))
            LazyColumn(verticalArrangement = Arrangement.spacedBy(3.dp)) {
                item(key = knowledgeTree.path) {
                    KnowledgeTreeNodeView(
                        node = knowledgeTree,
                        depth = 0,
                        expandedDirs = expandedDirs,
                        selectedPath = store.selectedSourcePath,
                        onToggleDirectory = { path ->
                            expandedDirs = if (path in expandedDirs) expandedDirs - path else expandedDirs + path
                        },
                        onSelectFile = { path ->
                            expanded = emptySet()
                            query = ""
                            locateSource(path)
                        },
                        onRename = { node -> if (node.path != "knowledge-base") renameTarget = node },
                    )
                }
            }
        }
        Spacer(Modifier.width(10.dp))
        Box(Modifier.fillMaxHeight().width(1.dp).background(MaterialTheme.colorScheme.outlineVariant))
        Spacer(Modifier.width(10.dp))
        Box(Modifier.weight(1f).fillMaxHeight()) {
            Column(
                Modifier.fillMaxSize().widthIn(max = 1440.dp).align(Alignment.Center),
            ) {
        OutlinedTextField(
            value = query,
            onValueChange = { query = it },
            modifier = Modifier.fillMaxWidth(),
            placeholder = { Text("搜索题目关键词…") },
            singleLine = true,
        )
        Spacer(Modifier.height(8.dp))
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("搜索范围", style = ui.typography.secondary, color = Theme.Muted)
            QuestionSearchScope.entries.forEach { scope ->
                val active = searchScope == scope
                Text(
                    scope.label,
                    Modifier
                        .clickable { searchScope = scope }
                        .background(if (active) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent, MaterialTheme.shapes.small)
                        .padding(horizontal = 9.dp, vertical = 4.dp),
                    fontSize = ui.typography.secondary.fontSize,
                    color = if (active) Theme.Accent else Theme.Muted,
                    fontWeight = if (active) FontWeight.Bold else FontWeight.Normal,
                )
            }
        }
        Spacer(Modifier.height(6.dp))
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("同源题库", style = ui.typography.sectionTitle, color = Theme.Accent)
            Text("${if (query.isBlank()) store.sourceQuestions.size else visible.size} 题", style = ui.typography.caption, color = Theme.Muted)
            Spacer(Modifier.weight(1f))
            if (query.isBlank()) {
                OutlinedButton(
                    onClick = {
                        reorderMode = !reorderMode
                        draggingKey = null
                        dragTargetIndex = null
                        dragPointerY = 0f
                        dragGrabOffset = 0f
                    },
                    contentPadding = PaddingValues(horizontal = 12.dp, vertical = 5.dp),
                ) {
                    Text(if (reorderMode) "完成排序" else "调整顺序", fontSize = 12.sp)
                }
            }
            Box {
                OutlinedButton(
                    onClick = { showMoreActions = true },
                    contentPadding = PaddingValues(horizontal = 12.dp, vertical = 5.dp),
                ) { Text("更多", fontSize = 12.sp) }
                DropdownMenu(
                    expanded = showMoreActions,
                    onDismissRequest = { showMoreActions = false },
                ) {
                    DropdownMenuItem(
                        text = { Text("新建单个题目") },
                        onClick = { showMoreActions = false; showCreateSingle = true },
                    )
                    DropdownMenuItem(
                        text = { Text("批量新建题目") },
                        onClick = { showMoreActions = false; showCreateBatch = true },
                    )
                }
            }
            Spacer(Modifier.width(12.dp))
            SelectionContainer {
                Text("${store.selectedSourcePath} · 文件即题库", style = ui.typography.caption, color = Theme.Muted, maxLines = 1)
            }
        }
        Spacer(Modifier.height(6.dp))
        if (SourceQuestions.isSupportedPath(store.selectedSourcePath, store.settings.sourceQuestionPaths)) {
            Text(
                if (reorderMode) "排序模式：按住任意题目卡片拖动换位，松开后自动保存并重新编号。"
                else if (query.isBlank()) "点击题目显示答案；需要调整顺序时点击右上角「调整顺序」。"
                else "点击题目显示答案；搜索结果仅供查看，清空搜索后可调整顺序。",
                fontSize = 11.sp,
                color = Theme.Muted,
            )
        } else {
            Text("该文档已纳入目录映射，但当前版本暂未接入 Q 题目解析。", fontSize = 11.sp, color = Theme.WarnOrange)
        }
        Spacer(Modifier.height(8.dp))
        LazyColumn(Modifier.fillMaxSize(), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            if (visible.isEmpty()) item { Text("没有匹配的题目。", fontSize = 13.sp, color = Theme.Muted) }
            items(documentItems, key = { item ->
                when (item) {
                    is SourceDocumentItem.Question -> sourceQuestionKey(item.entry)
                    is SourceDocumentItem.Section -> "section:${item.heading.startOffset}"
                }
            }) { item ->
                if (item is SourceDocumentItem.Section) {
                    Row(
                        Modifier.fillMaxWidth()
                            .background(Theme.Accent.copy(alpha = 0.1f), MaterialTheme.shapes.small)
                            .padding(horizontal = 12.dp, vertical = 9.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text("§", color = Theme.Accent, fontWeight = FontWeight.Bold)
                        Spacer(Modifier.width(8.dp))
                        Text(item.heading.title, color = Theme.Accent, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                    }
                    return@items
                }
                val entry = (item as SourceDocumentItem.Question).entry
                val entryKey = sourceQuestionKey(entry)
                val questionIndex = store.sourceQuestions.indexOfFirst { sourceQuestionKey(it) == entryKey }
                val displayIndex = renderedQuestions.indexOfFirst { sourceQuestionKey(it) == entryKey }
                val isExpanded = entryKey in expanded
                val isDragging = draggingKey == entryKey
                val canReorder = reorderMode && query.isBlank() && questionIndex >= 0 && visible.size == store.sourceQuestions.size
                val cardElevation by animateDpAsState(
                    targetValue = if (isDragging) 12.dp else 0.dp,
                    animationSpec = tween(180),
                    label = "question-card-elevation",
                )
                val cardScale by animateFloatAsState(
                    targetValue = if (isDragging) 1.015f else 1f,
                    animationSpec = tween(180),
                    label = "question-card-scale",
                )
                val cardTop = cardTops[entryKey] ?: 0f
                Column(
                    Modifier.fillMaxWidth()
                        .onGloballyPositioned { coordinates ->
                            cardTops[entryKey] = coordinates.positionInParent().y
                        }
                        .zIndex(if (isDragging) 2f else 0f)
                        .graphicsLayer {
                            scaleX = cardScale
                            scaleY = cardScale
                            translationY = if (isDragging) dragPointerY - dragGrabOffset - cardTop else 0f
                        }
                        .shadow(cardElevation, MaterialTheme.shapes.small)
                        .background(
                            if (isExpanded) Theme.Accent.copy(alpha = 0.08f)
                            else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
                            MaterialTheme.shapes.small,
                        )
                        .border(
                            1.dp,
                            if (isDragging) Theme.Accent
                            else if (reorderMode) Theme.Accent.copy(alpha = 0.42f)
                            else if (isExpanded) Theme.Accent.copy(alpha = 0.42f)
                            else MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.28f),
                            MaterialTheme.shapes.small,
                        )
                        .padding(ui.spacing.card)
                        .pointerInput(entryKey, canReorder) {
                            if (!canReorder) return@pointerInput
                            var accumulatedDistance = 0f
                            detectDragGestures(
                                onDragStart = {
                                    draggingKey = entryKey
                                    dragTargetIndex = questionIndex
                                    dragGrabOffset = it.y
                                    dragPointerY = cardTop + it.y
                                },
                                onDragEnd = {
                                    val target = dragTargetIndex
                                    val from = questionIndex
                                    if (target != null && target != from) {
                                        store.reorderSourceQuestions(store.sourceQuestions.toList(), from, target)
                                    }
                                    draggingKey = null
                                    dragTargetIndex = null
                                    dragPointerY = 0f
                                    dragGrabOffset = 0f
                                },
                                onDragCancel = {
                                    draggingKey = null
                                    dragTargetIndex = null
                                    dragPointerY = 0f
                                    dragGrabOffset = 0f
                                },
                                onDrag = { change, dragAmount ->
                                    change.consume()
                                    var target = dragTargetIndex ?: questionIndex
                                    dragPointerY = (cardTops[entryKey] ?: cardTop) + change.position.y
                                    accumulatedDistance += dragAmount.y
                                    while (accumulatedDistance > 36f && target < store.sourceQuestions.lastIndex) {
                                        target++
                                        accumulatedDistance -= 36f
                                    }
                                    while (accumulatedDistance < -36f && target > 0) {
                                        target--
                                        accumulatedDistance += 36f
                                    }
                                    if (target != dragTargetIndex) dragTargetIndex = target
                                },
                            )
                        },
                ) {
                    Row(
                        Modifier.fillMaxWidth(),
                        verticalAlignment = Alignment.Top,
                    ) {
                        if (reorderMode) {
                            Surface(
                                color = if (isDragging) Theme.Accent.copy(alpha = 0.22f) else Theme.Accent.copy(alpha = 0.10f),
                                shape = MaterialTheme.shapes.small,
                            ) {
                                Text(
                                    "${displayIndex + 1}",
                                    Modifier.padding(horizontal = 7.dp, vertical = 3.dp),
                                    color = Theme.Accent,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 12.sp,
                                )
                            }
                            Spacer(Modifier.width(8.dp))
                        }
                        Column(
                            Modifier.weight(1f).singleClickWithoutConsumingSelection {
                                locateSource(entry.sourcePath)
                                expanded = if (isExpanded) expanded - entryKey else expanded + entryKey
                            },
                        ) {
                            Text("Q${entry.number}", fontSize = 11.sp, color = Theme.Muted)
                            Spacer(Modifier.height(2.dp))
                            SelectionContainer {
                                Text(entry.question, style = ui.typography.itemTitle)
                            }
                            if (searchScope == QuestionSearchScope.ALL && query.isNotBlank()) {
                                Text(entry.sourcePath, fontSize = 10.sp, color = Theme.Accent, maxLines = 1)
                            }
                        }
                    }
                    if (isExpanded) {
                        Spacer(Modifier.height(10.dp))
                        if (entry.answer.isBlank()) {
                            Text("暂无答案", fontSize = 12.sp, color = Theme.WarnOrange)
                        } else {
                            Surface(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .singleClickWithoutConsumingSelection {
                                        if (store.settings.clickAnswerToEdit) editingEntry = entry
                                    },
                                shape = MaterialTheme.shapes.small,
                                color = if (store.settings.markdownStyle == "classic") {
                                    Theme.OkGreen.copy(alpha = 0.10f)
                                } else {
                                    MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.55f)
                                },
                            ) {
                                Column(Modifier.padding(horizontal = 12.dp, vertical = 10.dp)) {
                                    Text("答案", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = if (store.settings.markdownStyle == "classic") Theme.OkGreen else Theme.Accent)
                                    Spacer(Modifier.height(4.dp))
                                    CompositionLocalProvider(
                                        LocalContentColor provides if (store.settings.markdownStyle == "classic") {
                                            Theme.OkGreen.copy(alpha = 0.92f)
                                        } else {
                                            MaterialTheme.colorScheme.onSurface
                                        },
                                    ) {
                                        SelectionContainer {
                                            MarkdownText(entry.answer, style = store.settings.markdownStyle)
                                        }
                                    }
                                }
                            }
                        }
                        Spacer(Modifier.height(7.dp))
                        Text("编辑", Modifier.clickable { editingEntry = entry }, fontSize = 13.sp, color = Theme.Accent)
                    }
                }
                if (canReorder && dragTargetIndex == questionIndex && draggingKey != null && questionIndex == store.sourceQuestions.lastIndex) {
                    Spacer(Modifier.height(3.dp))
                    Box(
                        Modifier.fillMaxWidth()
                            .height(3.dp)
                            .background(Theme.Accent, MaterialTheme.shapes.small),
                    )
                }
            }
        }
        }
    }
        }
    renameTarget?.let { node ->
        RenameKnowledgeNodeDialog(store, node) { renameTarget = null }
    }
    if (showCreateSingle) {
        CreateSourceQuestionDialog(store, selectedMappedDocument) { showCreateSingle = false }
    }
    if (showCreateBatch) {
        BatchCreateSourceQuestionsDialog(store, selectedMappedDocument) { showCreateBatch = false }
    }
    editingEntry?.let { entry ->
        EditSourceQuestionDialog(
            store = store,
            entries = visible,
            initialIndex = visible.indexOfFirst { sourceQuestionKey(it) == sourceQuestionKey(entry) },
            onDismiss = { editingEntry = null },
        )
    }
}

/** 单击打开编辑，拖动时把鼠标事件留给 SelectionContainer 做划词。 */
private fun Modifier.singleClickWithoutConsumingSelection(onClick: () -> Unit): Modifier =
    pointerInput(onClick) {
        awaitPointerEventScope {
            var pressed = false
            var moved = false
            var downX = 0f
            var downY = 0f
            while (true) {
                val event = awaitPointerEvent(PointerEventPass.Initial)
                val change = event.changes.firstOrNull() ?: continue
                when (event.type) {
                    PointerEventType.Press -> {
                        pressed = true
                        moved = false
                        downX = change.position.x
                        downY = change.position.y
                    }
                    PointerEventType.Move -> if (pressed && ((change.position.x - downX) * (change.position.x - downX) + (change.position.y - downY) * (change.position.y - downY) > 36f)) moved = true
                    PointerEventType.Release -> {
                        if (pressed && !moved) onClick()
                        pressed = false
                    }
                }
            }
        }
    }

@Composable
private fun KnowledgeTreeNodeView(
    node: KnowledgeTreeNode,
    depth: Int,
    expandedDirs: Set<String>,
    selectedPath: String,
    onToggleDirectory: (String) -> Unit,
    onSelectFile: (String) -> Unit,
    onRename: (KnowledgeTreeNode) -> Unit,
) {
    val isExpanded = node.path in expandedDirs
    val selected = !node.isDirectory && node.path == selectedPath
    val bringIntoViewRequester = remember { BringIntoViewRequester() }
    LaunchedEffect(selected) {
        if (selected) bringIntoViewRequester.bringIntoView()
    }
    Row(
        Modifier.fillMaxWidth()
            .bringIntoViewRequester(bringIntoViewRequester)
            .background(
                if (selected) Theme.Accent.copy(alpha = 0.18f) else androidx.compose.ui.graphics.Color.Transparent,
                MaterialTheme.shapes.small,
            )
            .clickable {
                if (node.isDirectory) onToggleDirectory(node.path) else onSelectFile(node.path)
            }
            .pointerInput(node.path) {
                awaitPointerEventScope {
                    while (true) {
                        val event = awaitPointerEvent()
                        if (event.type == PointerEventType.Press && event.buttons.isSecondaryPressed) {
                            event.changes.forEach { it.consume() }
                            onRename(node)
                        }
                    }
                }
            }
            .padding(start = (depth * 16).dp, end = 6.dp, top = 7.dp, bottom = 7.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            if (node.isDirectory) (if (isExpanded) "▾" else "▸") else "  ",
            modifier = Modifier.width(18.dp), color = Theme.Muted, fontSize = 13.sp,
        )
        Text(
            if (node.isDirectory) "▰" else "M↓",
            modifier = Modifier.width(28.dp),
            color = if (selected) Theme.Accent else Theme.Muted,
            fontSize = if (node.isDirectory) 13.sp else 10.sp,
        )
        Text(
            node.name,
            color = if (selected) Theme.Accent else MaterialTheme.colorScheme.onSurface,
            fontSize = if (node.isDirectory) 14.sp else 13.sp,
            maxLines = 2,
        )
    }
    if (node.isDirectory && isExpanded) {
        node.children.forEach { child ->
            KnowledgeTreeNodeView(child, depth + 1, expandedDirs, selectedPath, onToggleDirectory, onSelectFile, onRename)
        }
    }
}

@Composable
private fun CreateSourceQuestionDialog(
    store: AppStore,
    targetPath: String,
    onDismiss: () -> Unit,
) {
    var question by remember { mutableStateOf("") }
    val nextNumber = remember(targetPath) { store.nextSourceQuestionNumber(targetPath) }
    var numberText by remember(targetPath) { mutableStateOf(nextNumber.toString()) }
    val number = numberText.toIntOrNull()
    val duplicate = question.trim().isNotBlank() && question.trim() in remember(targetPath) { store.sourceQuestionTexts(targetPath) }
    AlertDialog(
        onDismissRequest = onDismiss,
        modifier = Modifier.width(760.dp),
        properties = DialogProperties(usePlatformDefaultWidth = false),
        title = { Text("新建题目") },
        confirmButton = {
            Button(
                enabled = targetPath.isNotBlank() && question.isNotBlank() && number != null && number > 0 && !duplicate,
                onClick = {
                    if (number != null && store.createSourceQuestionAt(targetPath, SourceQuestions.Draft(question, ""), number)) onDismiss()
                },
            ) { Text("新建题目") }
        },
        dismissButton = { OutlinedButton(onClick = onDismiss) { Text("取消") } },
        text = {
            Column(
                Modifier.fillMaxWidth().heightIn(max = 560.dp).verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                Text("当前文档", fontWeight = FontWeight.SemiBold)
                Text(targetPath.ifBlank { "请先在左侧选择 Markdown 文档" }, fontSize = 12.sp, color = if (targetPath.isBlank()) Theme.WarnOrange else Theme.Accent)
                Text("输入插入位置，默认填入第 $nextNumber 题；已有题目会向后顺延。", fontSize = 11.sp, color = Theme.Muted)
                OutlinedTextField(
                    value = numberText,
                    onValueChange = { value -> if (value.all { it.isDigit() } && value.length <= 6) numberText = value },
                    modifier = Modifier.width(180.dp),
                    label = { Text("题目序号") },
                    singleLine = true,
                )
                if (number != null && number <= 0) Text("题目序号必须是正整数。", fontSize = 12.sp, color = Theme.WarnOrange)
                OutlinedTextField(
                    question,
                    { question = it },
                    Modifier.fillMaxWidth(),
                    label = { Text("题目") },
                    minLines = 3,
                )
                if (question.isNotBlank()) {
                    Surface(color = Theme.Accent.copy(alpha = 0.08f), shape = MaterialTheme.shapes.small) {
                        Text("将新建题目：${question.trim()}", Modifier.padding(10.dp), color = Theme.Accent)
                    }
                }
                if (duplicate) Text("该文档已有相同题目，请修改题面。", fontSize = 12.sp, color = Theme.WarnOrange)
            }
        },
    )
}

@Composable
private fun BatchCreateSourceQuestionsDialog(
    store: AppStore,
    targetPath: String,
    onDismiss: () -> Unit,
) {
    var input by remember { mutableStateOf("") }
    val drafts = remember(input) { SourceQuestions.parseBatch(input) }
    val duplicateCount = drafts.groupingBy { it.question }.eachCount().count { it.value > 1 }
    val existingQuestions = remember(targetPath) { store.sourceQuestionTexts(targetPath) }
    val existingDuplicateCount = drafts.count { it.question.trim() in existingQuestions }
    AlertDialog(
        onDismissRequest = onDismiss,
        modifier = Modifier.width(820.dp),
        properties = DialogProperties(usePlatformDefaultWidth = false),
        title = { Text("批量新建题目") },
        confirmButton = {
            Button(
                enabled = targetPath.isNotBlank() && drafts.isNotEmpty() && duplicateCount == 0 && existingDuplicateCount == 0,
                onClick = {
                    if (store.createSourceQuestions(targetPath, drafts)) onDismiss()
                },
            ) { Text("写入 ${drafts.size} 道题目") }
        },
        dismissButton = { OutlinedButton(onClick = onDismiss) { Text("取消") } },
        text = {
            Column(
                Modifier.fillMaxWidth().heightIn(max = 600.dp).verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                Text("当前文档", fontWeight = FontWeight.SemiBold)
                Text(targetPath.ifBlank { "请先在左侧选择 Markdown 文档" }, fontSize = 12.sp, color = if (targetPath.isBlank()) Theme.WarnOrange else Theme.Accent)
                Text("每行输入一道题目，系统会自动生成题号和空答案。", fontSize = 11.sp, color = Theme.Muted)
                OutlinedTextField(
                    input,
                    { input = it },
                    Modifier.fillMaxWidth(),
                    label = { Text("题目列表（一行一道）") },
                    minLines = 14,
                    maxLines = 24,
                )
                when {
                    input.isBlank() -> Text("尚未输入题目。", fontSize = 12.sp, color = Theme.Muted)
                    drafts.isEmpty() -> Text("请输入至少一道题目，每行一道。", fontSize = 12.sp, color = Theme.WarnOrange)
                    duplicateCount > 0 -> Text("发现重复题目，请修改后再写入。", fontSize = 12.sp, color = Theme.WarnOrange)
                    existingDuplicateCount > 0 -> Text("目标文档中已有 $existingDuplicateCount 道同名题目，请修改后再写入。", fontSize = 12.sp, color = Theme.WarnOrange)
                    else -> Text("已识别 ${drafts.size} 道题目，写入时会从源文档最大题号之后连续编号。", fontSize = 12.sp, color = Theme.OkGreen)
                }
            }
        },
    )
}

@Composable
private fun RenameKnowledgeNodeDialog(
    store: AppStore,
    node: KnowledgeTreeNode,
    onDismiss: () -> Unit,
) {
    var name by remember(node.path) { mutableStateOf(node.name) }
    fun save() {
        if (store.renameKnowledgeNode(node.path, name)) onDismiss()
    }
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(if (node.isDirectory) "重命名目录" else "重命名文件") },
        confirmButton = {
            Button(onClick = ::save) { Text("保存") }
        },
        dismissButton = { OutlinedButton(onClick = onDismiss) { Text("取消") } },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(
                    value = name,
                    onValueChange = { name = it },
                    modifier = Modifier.fillMaxWidth().onPreviewKeyEvent { event ->
                        if (event.key == Key.Enter && event.type == KeyEventType.KeyUp) {
                            save()
                            true
                        } else {
                            false
                        }
                    },
                    singleLine = true,
                    label = { Text(if (node.isDirectory) "目录名" else "文件名") },
                )
                Text(
                    if (node.isDirectory) "不能包含 / 或 \\。" else "文件名会保留 .md 后缀。",
                    fontSize = 11.sp,
                    color = Theme.Muted,
                )
            }
        },
    )
}

@Composable
private fun EditSourceQuestionDialog(
    store: AppStore,
    entries: List<SourceQuestions.Entry>,
    initialIndex: Int,
    onDismiss: () -> Unit,
) {
    // 保存会触发 AppStore 重载；编辑会话必须使用稳定快照，不能跟着外层 visible 短暂清空。
    val stableEntries = remember { entries.toList() }
    var currentIndex by remember { mutableStateOf(initialIndex.coerceIn(0, (stableEntries.size - 1).coerceAtLeast(0))) }
    var isSaving by remember { mutableStateOf(false) }
    val safeIndex = safeQuestionIndex(currentIndex, stableEntries.size)
    if (safeIndex == null) {
        LaunchedEffect(Unit) { onDismiss() }
        return
    }
    val entry = stableEntries[safeIndex]
    var question by remember(entry.id) { mutableStateOf(entry.question) }
    var answer by remember(entry.id) { mutableStateOf(entry.answer) }
    fun saveAndMove(target: Int): Boolean {
        if (question.isBlank()) return false
        if (!store.saveSourceQuestion(entry, question, answer)) return false
        currentIndex = target
        return true
    }
    fun saveAndMoveOnce(target: Int) {
        if (!canNavigateQuestionEditor(isSaving, target, stableEntries.size)) return
        isSaving = true
        try {
            saveAndMove(target)
        } finally {
            isSaving = false
        }
    }
    AlertDialog(
        onDismissRequest = onDismiss,
        modifier = Modifier.width(820.dp),
        properties = DialogProperties(usePlatformDefaultWidth = false),
        title = { Text("编辑 Q${entry.number}（${safeIndex + 1}/${stableEntries.size}）") },
        confirmButton = {
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                val previous = adjacentQuestionIndex(safeIndex, stableEntries.size, -1)
                val next = adjacentQuestionIndex(safeIndex, stableEntries.size, 1)
                OutlinedButton(
                    enabled = !isSaving && previous != null,
                    onClick = { previous?.let { saveAndMoveOnce(it) } },
                ) {
                    Text("保存并上一个")
                }
                OutlinedButton(
                    enabled = !isSaving && next != null,
                    onClick = { next?.let { saveAndMoveOnce(it) } },
                ) {
                    Text("保存并下一个")
                }
                Button(onClick = {
                    if (!isSaving && question.isNotBlank()) {
                        isSaving = true
                        try {
                            if (store.saveSourceQuestion(entry, question, answer)) onDismiss()
                        } finally {
                            isSaving = false
                        }
                    }
                }) { Text("保存到源文档") }
            }
        },
        dismissButton = { OutlinedButton(onClick = onDismiss) { Text("取消") } },
        text = {
            Column(
                Modifier.fillMaxWidth().heightIn(max = 560.dp).verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                OutlinedTextField(question, { question = it }, Modifier.fillMaxWidth(), label = { Text("题目") }, minLines = 2)
                OutlinedTextField(
                    answer,
                    { answer = it },
                    Modifier.fillMaxWidth(),
                    label = { Text("答案 Markdown") },
                    minLines = 8,
                    maxLines = 16,
                )
                Text("保存后直接修改 ${entry.sourcePath}", fontSize = 11.sp, color = Theme.Muted)
            }
        },
    )
}
